export const JOY_SPARKS = [
  {
    id: "1",
    title: "Doodle Break",
    description: "Grab a pen and doodle whatever comes to mind for 2 minutes. No rules, no judgment.",
    category: "creative",
    duration: "2 min",
    emoji: "🎨",
  },
  {
    id: "2",
    title: "Playlist Mood",
    description: "Pick 3 songs that match your current vibe. Let the music speak for you.",
    category: "music",
    duration: "5 min",
    emoji: "🎵",
  },
  {
    id: "3",
    title: "Cloud Watch",
    description: "Look outside or close your eyes. Imagine shapes in the clouds or ceiling.",
    category: "mindfulness",
    duration: "3 min",
    emoji: "☁️",
  },
  {
    id: "4",
    title: "Gratitude Snap",
    description: "Take a photo of something small that makes you smile today.",
    category: "gratitude",
    duration: "1 min",
    emoji: "📸",
  },
  {
    id: "5",
    title: "Dance It Out",
    description: "Put on your favorite song and move however feels good. Eyes closed, no mirrors.",
    category: "movement",
    duration: "3 min",
    emoji: "💃",
  },
  {
    id: "6",
    title: "Breathe & Ground",
    description: "4 counts in, hold 4, out 4. Feel your feet on the floor. You're here, you're okay.",
    category: "mindfulness",
    duration: "2 min",
    emoji: "🌬️",
  },
  {
    id: "7",
    title: "Kind Words",
    description: "Write yourself a short note — what would you say to your best friend right now?",
    category: "affirmation",
    duration: "3 min",
    emoji: "💌",
  },
  {
    id: "8",
    title: "Stretch & Yawn",
    description: "Reach up high, stretch to both sides, roll your neck. Let your body wake up gently.",
    category: "movement",
    duration: "2 min",
    emoji: "🌅",
  },
];

export const CHALLENGES = [
  {
    id: "1",
    title: "7 Days of Joy Sparks",
    description: "Complete one Joy Spark activity every day for a week.",
    duration: "7 days",
    participants: 234,
    difficulty: "gentle",
    emoji: "✨",
  },
  {
    id: "2",
    title: "Mirror Kindness",
    description: "Each morning, say one kind thing to yourself in the mirror.",
    duration: "5 days",
    participants: 189,
    difficulty: "gentle",
    emoji: "🪞",
  },
  {
    id: "3",
    title: "Mood Music Journal",
    description: "Create a playlist that tracks your mood each day this week.",
    duration: "7 days",
    participants: 156,
    difficulty: "moderate",
    emoji: "🎶",
  },
  {
    id: "4",
    title: "Digital Detox Hour",
    description: "Spend one hour each day without screens. Journal what you notice.",
    duration: "5 days",
    participants: 312,
    difficulty: "moderate",
    emoji: "📵",
  },
  {
    id: "5",
    title: "Compliment Chain",
    description: "Give one genuine compliment to someone different each day.",
    duration: "7 days",
    participants: 445,
    difficulty: "gentle",
    emoji: "💬",
  },
  {
    id: "6",
    title: "Nature Connection",
    description: "Spend 10 minutes outside each day, just observing without your phone.",
    duration: "5 days",
    participants: 201,
    difficulty: "gentle",
    emoji: "🌿",
  },
];

export const MOOD_OPTIONS = [
  { emoji: "😊", label: "Happy", value: 5 },
  { emoji: "😌", label: "Calm", value: 4 },
  { emoji: "😐", label: "Neutral", value: 3 },
  { emoji: "😔", label: "Low", value: 2 },
  { emoji: "😢", label: "Sad", value: 1 },
];

export const SUGGESTED_PROMPTS = [
  "I'm feeling stressed lately",
  "Give me a Joy Spark activity",
  "Help me with body positivity",
  "I need some motivation today",
  "Let's try a breathing exercise",
  "I want to feel better about myself",
];

export const COMMUNITY_POSTS = [
  {
    id: "1",
    author: "anonymous_glow",
    content: "Tried the Doodle Break today and ended up drawing for 20 minutes. Felt so much lighter after! 🎨",
    likes: 24,
    timeAgo: "2h ago",
    tag: "Joy Spark",
  },
  {
    id: "2",
    author: "zen_vibes",
    content: "Day 3 of Mirror Kindness challenge. It felt weird at first but today I actually smiled at myself. Progress!",
    likes: 45,
    timeAgo: "4h ago",
    tag: "Challenge",
  },
  {
    id: "3",
    author: "moonlight_dancer",
    content: "Just did Dance It Out with my favorite song. No mirrors, no judgment — just pure joy. This is what movement should feel like. 💃",
    likes: 67,
    timeAgo: "6h ago",
    tag: "Joy Spark",
  },
  {
    id: "4",
    author: "quiet_storm",
    content: "Feeling low today but the Breathe & Ground spark helped me come back to the present. Small wins matter.",
    likes: 38,
    timeAgo: "8h ago",
    tag: "Wellness",
  },
  {
    id: "5",
    author: "sunrise_kid",
    content: "Completed the 7 Days of Joy Sparks challenge! My joy score went from 2.3 to 3.8 this week 🌟",
    likes: 89,
    timeAgo: "1d ago",
    tag: "Achievement",
  },
];
